apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - athena-standard.yaml
  - athena-packet-lab.yaml
  - athena-exploit-lab.yaml
  - network-policy-default-deny.yaml
  - network-policy-lab-egress.yaml
  - network-policy-soc-deny.yaml
